service: serverless-final-todo

custom:
  tableName: ${self:service}-${opt:stage}

provider:
  name: aws
  runtime: nodejs8.10
  stackName: ${self:service}-${opt:stage}
  environment:
    TABLE_NAME: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DeleteItem
        - dynamodb:PutItem
        - dynamodb:Scan
      Resource:
        Fn::Join:
          - ':'
          - - arn:aws:dynamodb
            - Ref: AWS::Region
            - Ref: AWS::AccountId
            - table/${self:custom.tableName}

package:
  include:
    - handler.js

functions:
  deleteTodo:
    handler: handler.deleteTodo
    events:
      - http:
          cors: true
          method: delete
          path: /{id}
          request:
            parameters:
              paths:
                id: true
  readTodos:
    handler: handler.readTodos
    events:
      - http:
          cors: true
          method: get
          path: /
  writeTodo:
    handler: handler.writeTodo
    events:
      - http:
          cors: true
          method: put
          path: /{id}
          request:
            parameters:
              paths:
                id: true

resources:
  Resources:
    DatabaseTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        TableName: ${self:custom.tableName}
    WebsiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        Tags:
          - Key: Public
            Value: Static assets for DevOps-Girls/DevOps-Girls-Bootcamp-4
        WebsiteConfiguration:
          IndexDocument: index.html
    WebsiteBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Principal: '*'
              Resource:
                Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - Ref: WebsiteBucket
                    - /*
        Bucket:
          Ref: WebsiteBucket

  Outputs:
    WebsiteBucketName:
      Value:
        Ref: WebsiteBucket
    WebsiteURL:
      Value:
        Fn::GetAtt:
          - WebsiteBucket
          - WebsiteURL
