service: serverless-todo

custom:
  tableName: ${self:service}-${opt:stage}

provider:
  name: aws
  runtime: nodejs8.10
  stackName: ${self:service}-${opt:stage}
  environment:
    TABLE_NAME: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DeleteItem
        - dynamodb:PutItem
        - dynamodb:Scan
      Resource:
        Fn::Join:
          - ':'
          - - arn:aws:dynamodb
            - Ref: AWS::Region
            - Ref: AWS::AccountId
            - table/${self:custom.tableName}

package:
  include:
    - handler.js

functions:
  deleteTodo:
    handler: handler.deleteTodo
    events:
      - http:
          method: delete
          path: /{id}
          request:
            parameters:
              paths:
                id: true
  readTodos:
    handler: handler.readTodos
    events:
      - http:
          method: get
          path: /
  writeTodo:
    handler: handler.writeTodo
    events:
      - http:
          method: put
          path: /{id}
          request:
            parameters:
              paths:
                id: true

resources:
  Resources:
    DatabaseTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        TableName: ${self:custom.tableName}
