service: serverless-starter-todo

provider:
  name: aws
  runtime: nodejs8.10
  stackName: serverless-starter-todo-dev
  stage: dev

package:
  include:
    - greeter.js
    - handler.js

functions:
  TodoApi:
    name: serverless-starter-todo-api-dev
    handler: greeter.handleRequest
    events:
      - http:
          cors: true
          method: any
          path: /{proxy+}
